### ISSUE TITLE
[BUG] Failed to load data files with ITK when using Clara Train docker image

### ISSUE THREAD

**Issue by AndreasHeumann** [NVIDIA/clara-viz#12]
**Describe the bug**

Loading data files with the DataDefinition class which is using ITK fails when using Clara Train docker image.

**Steps/Code to reproduce bug**

```
/clara-viz/notebooks$ docker run --rm -it --network host -e NVIDIA_DRIVER_CAPABILITIES=graphics,video,compute,utility -v $PWD:/notebooks nvcr.io/nvidia/clara-train-sdk:v4.0
...
# pip3 install clara-viz
# cd /notebooks
# python3
>>> from clara.viz.core import DataDefintion
>>> d = DataDefinition()
>>>d.append('data/syn3193805/img0066.nii.gz', 'DXYZ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/clara/viz/core/datadefinition.py", line 92, in append
    itk.CommonEnums.IOComponent_FLOAT: itk.F,
  File "/opt/conda/lib/python3.8/site-packages/clara/viz/core/importutil.py", line 154, in __getattr__
    raise self._exception
  File "/opt/conda/lib/python3.8/site-packages/clara/viz/core/importutil.py", line 118, in optional_import
    raise AssertionError
clara.viz.core.importutil.OptionalImportError: import itk.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
```

**Expected behavior**

File should be loaded without error

**Environment details (please complete the following information)**

- OS/Platform: Linux
- Python Version: 3.8.5
- Clara Viz Version: 0.1.2

**Additional context**

**Comment by AndreasHeumann** [comment]
Fixed with 0.1.3.
